---
- name: prepares a server to serve application
  hosts: all
  become: yes
  gather_facts: no

  vars_files:
    - vars.yml

  pre_tasks:
    - name: ensure system dependencies are installed
      yum: name={{ item }} state=present
      loop:
        - git
        - python3
        - python-setuptools

  roles:
    - gunicorn
